spring:
  profiles:
    include:
      - real
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
    open-in-view: false
spring.batch.job.names: ${job.name:NONE}
logging.level:
  org.springframework:
#    jdbc:
#      core:
#        JdbcTemplate: DEBUG
    batch:
      item:
        database: DEBUG
---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:jojoldu;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
      auto-commit: false
      idleTimeout: 10000      #10s
      maxLifetime: 180000     #3m
      maximumPoolSize: 5

logging:
  level:
    com.querydsl.sql: DEBUG

---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: jojoldu
      password: jojoldu1
      driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: aws
  datasource:
    hikari:
      jdbc-url: jdbc:mysql:aurora://cluster주소:포트,reader-cluster주소:포트/jojoldu?connectTimeout=1000&socketTimeout=600000
      username: jojoldu
      password: passwd
      driver-class-name: org.mariadb.jdbc.Driver
      auto-commit: false
      idleTimeout: 600000      #10m
      maxLifetime: 1800000     #30m
      maximumPoolSize: 10